name: Flutter CI

on:
  push:
    branches:
      - main
      - production
  pull_request:
    branches:
      - main

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Clean data
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Cache CocoaPods
        uses: actions/cache@v3
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods       

      - name: Build Flutter IPA
        run: |
          flutter build ios --release --no-codesign --verbose

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: my-app.ipa
          path: build/ios/iphoneos/*.ipa
